import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

interface Products {
  products: Product[];
}

interface Product {
  id: string;
  name: string;
  image: string;
  price: string;
  description: string;
}

const Home: NextPage<Products> = ({ products }) => {
  console.log("products", products);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to our shop!</h1>

        <p className={styles.description}>
          Pick whatever you like, worry about payment later!
        </p>

        <div className={styles.grid}>
          {products.map((product: Product) => {
            return (
              <a
                // href="https://nextjs.org/docs"
                href={product.id}
                className={styles.card}
                key={product.id}
              >
                <h2>{product.name}</h2>
                <h4>
                  <strong>Price: </strong>${product.price}
                </h4>
                <img
                  style={{ maxWidth: "250px" }}
                  src={product.image}
                  alt={`Photo of ${product.name}`}
                />
              </a>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  const client = new ApolloClient({
    uri: "https://reasonapps-gql-api.vercel.app/api/graphql",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query Product {
        products {
          id
          name
          image
          price
          description
        }
      }
    `,
  });

  console.log("data", data);

  return {
    props: {
      products: data.products,
    },
  };
};
